-- V10 — Assistant chat conversations ("threads") for the chat history UI.
CREATE TABLE assistant_conversation (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT       NOT NULL,
    title            VARCHAR(255),
    created_at       TIMESTAMP(6) NOT NULL,
    last_activity_at TIMESTAMP(6) NOT NULL,
    archived_at      TIMESTAMP(6) NULL,
    CONSTRAINT fk_assistant_conversation_user FOREIGN KEY (user_id) REFERENCES cafe_user(id)
);

-- Every message belongs to at most one conversation. NULL for rows created
-- before conversations existed (legacy single-thread history); they remain
-- visible via the legacy per-user /assistant/history endpoint.
ALTER TABLE assistant_message ADD COLUMN conversation_id BIGINT NULL;
ALTER TABLE assistant_message ADD CONSTRAINT fk_assistant_message_conversation
    FOREIGN KEY (conversation_id) REFERENCES assistant_conversation(id);

CREATE INDEX idx_assistant_conversation_user ON assistant_conversation(user_id);
CREATE INDEX idx_assistant_message_conversation ON assistant_message(conversation_id);