-- V13 — Phase 4 (Agentic AI): session audit trail + AI action audit log.

-- Login / logout history per user. Populated by the Spring Security login
-- event listener and the custom logout success handler; read back by the
-- assistant's getUserLoginHistory / getUserSessionActivity tools (gated on
-- the USER_MANAGEMENT permission).
CREATE TABLE user_session_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    username    VARCHAR(255) NOT NULL,
    event       VARCHAR(31)  NOT NULL,
    session_id  VARCHAR(63),
    occurred_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_user_session_log_user FOREIGN KEY (user_id) REFERENCES cafe_user(id)
);
CREATE INDEX idx_user_session_log_user ON user_session_log(user_id);

-- Audit trail for every AI-initiated action, kept DISTINCT from chat history.
-- Rows also act as the durable store for pending confirmations: a write tool
-- that needs user approval is recorded here with status PENDING_CONFIRMATION
-- first; the confirm/cancel endpoints flip it to EXECUTED / CANCELLED.
CREATE TABLE assistant_action_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    conversation_id BIGINT,
    tool            VARCHAR(63)  NOT NULL,
    params_json     TEXT,
    description     TEXT,
    status          VARCHAR(31)  NOT NULL,
    trigger_mode    VARCHAR(31),
    result_summary  TEXT,
    created_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_assistant_action_log_user FOREIGN KEY (user_id) REFERENCES cafe_user(id)
);
CREATE INDEX idx_assistant_action_log_user ON assistant_action_log(user_id);