-- V17 — Credential hardening + assistant daily quota.
--
-- 1. Lock the seeded placeholder logins. The V2/V5/V7 seed passwords are
--    publicly documented ("changeme123"), so anyone reaching the login page
--    could take the accounts over by completing the forced-change flow
--    themselves. These hashes match nothing: password login is impossible
--    until the bootstrap runner (first boot) issues random passwords, after
--    which an admin sets real ones. must_change_password stays enforced.
UPDATE cafe_user
SET password = '{locked}bootstrap-required',
    must_change_password = TRUE
WHERE username IN ('admin', 'staff', 'kitchen');

-- 2. Account lockout state for the login-abuse guard. NULL = never locked;
--    a future timestamp = rejecting logins until then (checked in
--    CustomUserDetailsService with the generic "invalid credentials" error,
--    so locked accounts are indistinguishable from unknown ones).
ALTER TABLE cafe_user
    ADD COLUMN locked_until TIMESTAMP NULL;

-- 3. Durable per-user daily assistant budget (production cost control).
--    One row per user per UTC day; the quota service increments it per
--    turn and refuses once the configured daily allowance is spent.
CREATE TABLE assistant_daily_usage (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT       NOT NULL,
    usage_day DATE         NOT NULL,
    turns     INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT fk_assistant_daily_usage_user FOREIGN KEY (user_id) REFERENCES cafe_user(id),
    CONSTRAINT uq_assistant_daily_usage_user_day UNIQUE (user_id, usage_day)
);
CREATE INDEX idx_assistant_daily_usage_user ON assistant_daily_usage(user_id);
