CREATE TABLE category (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    active      BOOLEAN NOT NULL
);

CREATE TABLE menu_item (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    price       NUMERIC(38, 2) NOT NULL,
    available   BOOLEAN NOT NULL,
    category_id BIGINT NOT NULL,
    CONSTRAINT fk_menu_item_category FOREIGN KEY (category_id) REFERENCES category(id)
);

CREATE TABLE cafe_order (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP(6),
    total_amount NUMERIC(38, 2),
    item_count   INTEGER
);

CREATE TABLE cafe_order_item (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT NOT NULL,
    menu_item_id BIGINT NOT NULL,
    item_name    VARCHAR(255),
    quantity     INTEGER NOT NULL,
    unit_price   NUMERIC(38, 2),
    subtotal     NUMERIC(38, 2),
    CONSTRAINT fk_order_item_order     FOREIGN KEY (order_id)     REFERENCES cafe_order(id),
    CONSTRAINT fk_order_item_menu_item FOREIGN KEY (menu_item_id) REFERENCES menu_item(id)
);