CREATE TABLE cafe_user (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(31)  NOT NULL
);

-- Seed one initial ADMIN user.
-- Password: changeme123 (BCrypt-hashed)
-- IMPORTANT: This is a placeholder password. Change it after first login
-- by updating the password hash in the database or through a future migration.
INSERT INTO cafe_user (username, password, role)
VALUES ('admin', '$2b$10$lwQwQK5wCJUaYBRnMjna9uNobt1TQY14vqAi7A4KvJ2ouoI52pp/q', 'ADMIN');