CREATE TABLE inventory (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_item_id       BIGINT NOT NULL UNIQUE,
    track_inventory    BOOLEAN NOT NULL DEFAULT FALSE,
    stock_quantity     INTEGER NOT NULL DEFAULT 0,
    low_stock_threshold INTEGER NOT NULL DEFAULT 0,
    last_updated_at    TIMESTAMP(6),
    CONSTRAINT fk_inventory_menu_item FOREIGN KEY (menu_item_id) REFERENCES menu_item(id)
);

INSERT INTO inventory (menu_item_id, track_inventory, stock_quantity, low_stock_threshold)
SELECT id, FALSE, 0, 0 FROM menu_item;