CREATE TABLE assistant_message (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    role       VARCHAR(31) NOT NULL,
    content    TEXT        NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_assistant_message_user FOREIGN KEY (user_id) REFERENCES cafe_user(id)
);